### ISSUE TITLE
Merge nightly into master branch to work with tf2.3?

### ISSUE THREAD

**Issue by marioecd** [tensorflow/io#1028]
The tf 2.3 release of Tensorflow has the code required by tfio gstpufs target build. When we make tfio master branch work with tf 2.3, can we merge tfio nightly branch into into the master?

**Comment by yongtang** [comment]
Thanks @marioecd for the reminder. We are in the process of release v0.14.0 (#1023) this week. Once v0.14.0 is released we will immediately switch to TF 2.3.

**Comment by yongtang** [comment]
@marioecd  The master branch has been updated and now it depends on 2.3.0rc0+. Please give it a try.

**Comment by lminer** [comment]
Any ideas when it will make it to the nightly? `pip install tensorflow-io-nightly` still install tf 2.2.0

**Comment by yongtang** [comment]
@lminer A new build of tensorflow-io-nightly is now available, which supports TF 2.3.0rc0:

https://pypi.org/project/tensorflow-io-nightly/

**Comment by marioecd** [comment]
Now I installed tfio with:
pip install tensorflow-io

to see if it has my bits; but when I ran my python test the [gstpu](https://github.com/tensorflow/io/blob/master/tensorflow_io/core/kernels/gstpufs/gs_tpu_file_system.cc#L27) does not appear registered. "File system scheme 'gstpu' not implemented"

This would work when I do bazel install:
bazel build -s --verbose_failures //tensorflow_io/...

Is the pip install the correct way to get the latest master branch?

**Comment by yongtang** [comment]
@marioecd the `pip install tensorflow-io` will only install the last stable version (v0.14.0) which does not have gstpu yet (v0.14.0 is based on TF 2.2.0 so could not apply gstpu.).

It is already in nightly build, you can use `pip install tensorflow-io-nightly` (depends on TF 2.3.0rc+) to give it a try.

gstpu will appear in the next stable release of v0.15.0 which will be released in a week or two once TF 2.3.0 final is released (TF already released 2.3.0rc2 and will release 2.3.0 next week I assume).

**Comment by marioecd** [comment]
Ah ok just tried 'pip install tensorflow-io-nightly' on a TF2.3 image but it didn't register 'gstpu' either.

**Comment by marioecd** [comment]
It worked when I installed tf-nightly though.
pip install tensorflow-io-nightly

**Comment by yongtang** [comment]
@marioecd  I tried and it looks to be fine. Maybe it is because of the pip cache issue on your local system?

Here are the steps (in docker to have a clean setup):
```
# run into docker
$ docker run -i -t --rm -v $PWD:/v -w /v --net=host ubuntu:20.04

# install python3
% apt-get -y -qq update && apt-get -y -qq install python3-pip

# install tensorflow-io-nightly, will automatically install TF 2.3.0rc
% python3 -m pip install -U tensorflow-io-nightly

# enter python3:
% python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow_io as tfio # note import tfio is needed to implicitly invoke schema gstpu and other file systems
>>> tf.io.read_file('gstpu://123')
2020-07-20 18:53:56.745958: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-07-20 18:53:56.745997: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-20 18:53:56.746036: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-21-87): /proc/driver/nvidia/version does not exist
2020-07-20 18:53:56.746402: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-20 18:53:56.769369: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2199995000 Hz
2020-07-20 18:53:56.769660: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x42692f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-20 18:53:56.769686: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-20 18:53:56.772146: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at whole_file_read_ops.cc:116 : Invalid argument: GCS path doesn't contain an object name: gstpu://123
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 561, in read_file
    return read_file_eager_fallback(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 599, in read_file_eager_fallback
    _result = _execute.execute(b"ReadFile", 1, inputs=_inputs_flat,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: GCS path doesn't contain an object name: gstpu://123 [Op:ReadFile]
>>> 

```

**Comment by marioecd** [comment]
I tried again, tensorflow-io-nightly on a new machine with TF 2.3 and it worked. Thanks!

**Comment by kvignesh1420** [comment]
@yongtang can this be closed?

**Comment by yongtang** [comment]
@kvignesh1420 Yes I think this issue has been resolved.
