### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.io'

### ISSUE THREAD

**Issue by minalmeg** [tensorflow/io#1453]
Python version - 3.7.5

Libs versions -
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post2
tensorflow-addons==0.7.1
tensorflow-datasets==4.3.0
tensorflow-estimator==2.1.0
tensorflow-gpu==2.1.0
tensorflow-hub==0.12.0
tensorflow-io==0.11.0
tensorflow-metadata==1.0.0
tensorflow-text==2.1.0rc0

```
python3 official/vision/beta/projects/movinet/train.py     --experiment=movinet_kinetics600     --mode=train     --model_dir=/tmp/movinet/     --config_file=${CONFIG_FILE}     --params_override=""     --gin_file=""     --gin_params=""     --tpu=""     --tf_data_service=""
2021-06-09 16:54:11.488388: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2021-06-09 16:54:11.488448: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2021-06-09 16:54:11.488458: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2021-06-09 16:54:11.970872: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-06-09 16:54:11.970895: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "official/vision/beta/projects/movinet/train.py", line 43, in <module>
    from official.common import registry_imports
  File "/home/cynapto/Desktop/3D-CNN/models/official/common/registry_imports.py", line 18, in <module>
    from official.nlp.configs import experiment_configs
  File "/home/cynapto/Desktop/3D-CNN/models/official/nlp/configs/experiment_configs.py", line 17, in <module>
    from official.nlp.configs import finetuning_experiments
  File "/home/cynapto/Desktop/3D-CNN/models/official/nlp/configs/finetuning_experiments.py", line 20, in <module>
    from official.nlp.data import question_answering_dataloader
  File "/home/cynapto/Desktop/3D-CNN/models/official/nlp/data/question_answering_dataloader.py", line 21, in <module>
    from official.core import input_reader
  File "/home/cynapto/Desktop/3D-CNN/models/official/core/input_reader.py", line 21, in <module>
    import tensorflow_datasets as tfds
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/__init__.py", line 53, in <module>
    from tensorflow_datasets import d4rl
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/d4rl/__init__.py", line 17, in <module>
    from tensorflow_datasets.d4rl.d4rl_mujoco_ant import D4rlMujocoAnt
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/d4rl/d4rl_mujoco_ant/__init__.py", line 18, in <module>
    from tensorflow_datasets.d4rl.d4rl_mujoco_ant.d4rl_mujoco_ant import D4rlMujocoAnt
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/d4rl/d4rl_mujoco_ant/d4rl_mujoco_ant.py", line 20, in <module>
    from tensorflow_datasets.d4rl import mujoco_dataset
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/d4rl/mujoco_dataset.py", line 22, in <module>
    from tensorflow_datasets.d4rl import dataset_utils
  File "/home/cynapto/Desktop/3D-CNN/models/venv/lib/python3.7/site-packages/tensorflow_datasets/d4rl/dataset_utils.py", line 21, in <module>
    from tensorflow.io import gfile
ModuleNotFoundError: No module named 'tensorflow.io'
```
I've tried in conda environment, in virtualenv. I've also tried tensorflow.io==0.12, but this issue still persists. 

Is there anything I'm missing?
Do I have to build tf.io from from source?

**Comment by kvignesh1420** [comment]
@minalmeg the import is as follows:
```
import tensorflow_io as tfio
import tensorflow as tf

tf.io.gfile(...)
```

tensorflow_io and tensorflow.io are different

**Comment by kvignesh1420** [comment]
closing as of now, please reopen the issue if you have further questions @minalmeg
