### ISSUE TITLE
`tensorflow_io` doesn't work with Cloud new alpha-TPUs?

### ISSUE THREAD

**Issue by vasudevgupta7** [tensorflow/io#1467]
Is tensorflow_io compatible with new alpha-TPUs? I am trying to use `decode_flac` but getting following error. Any solutions to this??

```

WARNING:tensorflow:AutoGraph could not transform <function decode_flac at 0x7f82400a6040> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unable to open file: libtensorflow_io.so, from paths: ['/home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['libtensorflow_framework.so.2: cannot open shared object file: No such file or directory']
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
2021-06-26 14:48:16.704169: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-06-26 14:48:16.704211: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2021-06-26 14:48:16.904596: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2021-06-26 14:48:16.904651: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    main(args, resolver)
  File "main.py", line 70, in main
    tr_dataset = LibriSpeechDataLoader(tr_data_args)(seed=args.seed)
  File "/home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py", line 43, in __call__
    dataset = self._build_and_fetch_dataset()
  File "/home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py", line 96, in _build_and_fetch_dataset
    input_dataset = input_dataset.map(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1861, in map
    return ParallelMapDataset(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4733, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3923, in __init__
    self._function = fn_factory()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3143, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3109, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3456, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3291, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3898, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3828, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in user code:

    /home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py:106 decode_sound  *
        audio = tfio.audio.decode_flac(audio, dtype=tf.int16)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/audio_ops.py:480 decode_flac  **
        return core_ops.io_audio_decode_flac(input, shape=shape, dtype=dtype, name=name)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:88 __getattr__
        return getattr(self._load(), attrb)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:84 _load
        self._mod = _load_library(self._library)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:69 _load_library
        raise NotImplementedError(

    NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
    caused by: ['libtensorflow_framework.so.2: cannot open shared object file: No such file or directory']

Traceback (most recent call last):
  File "main.py", line 135, in <module>
    main(args, resolver)
  File "main.py", line 70, in main
    tr_dataset = LibriSpeechDataLoader(tr_data_args)(seed=args.seed)
  File "/home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py", line 43, in __call__
    dataset = self._build_and_fetch_dataset()
  File "/home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py", line 96, in _build_and_fetch_dataset
    input_dataset = input_dataset.map(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1861, in map
    return ParallelMapDataset(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4733, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3923, in __init__
    self._function = fn_factory()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3143, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3109, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3456, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3291, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3898, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3828, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
NotImplementedError: in user code:

    /home/vasudevgupta/gsoc-wav2vec2/src/data_utils.py:106 decode_sound  *
        audio = tfio.audio.decode_flac(audio, dtype=tf.int16)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/audio_ops.py:480 decode_flac  **
        return core_ops.io_audio_decode_flac(input, shape=shape, dtype=dtype, name=name)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:88 __getattr__
        return getattr(self._load(), attrb)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:84 _load
        self._mod = _load_library(self._library)
    /home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/__init__.py:69 _load_library
        raise NotImplementedError(

    NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/home/vasudevgupta/.local/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
    caused by: ['libtensorflow_framework.so.2: cannot open shared object file: No such file or directory']
```

Thanks

**Comment by kvignesh1420** [comment]
@vasudevgupta7 seems like `tensorflow_io` is not properly installed in that environment. I am not sure about the new alpha-TPU env that you have mentioned, but I was able to decode flac files in the colab's TPU runtime env. Can you share more information on which `tensorflow_io` version you are using how you installed it? (from pip or via source)

**Comment by vasudevgupta7** [comment]
Hey @kvignesh1420, thanks for your reply. I installed it using pip: `pip3 install tensorflow_io`.

**Comment by kvignesh1420** [comment]
Is your TPU env different from colab?

**Comment by vasudevgupta7** [comment]
alpha-TPUs are different I guess (like they can be used like GPUs by direct ssh). I will share a reproducible script with you.

Thanks a lot!!

**Comment by vasudevgupta7** [comment]
Hey, this was just a dependency issue. It's resolved. So, closing this issue.

**Comment by kretes** [comment]
I face the same issue resulting in
```
 NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/root/.cache/pypoetry/virtualenvs/deeplearning-CRl2NYz6-py3.8/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
E       caused by: ['libtensorflow_framework.so.2: cannot open shared object file: No such file or directory']
```
In the environment have a custom wheel for tensorflow installed by poetry, and on top of that a `poetry run pip install --no-deps tensorflow-io tensorflow-io-gcs-filesystem` .
`--no-deps` is for tensorflow not being installed again, as it is already there

@vasudevgupta7 How exactly have you resolved this as a dependency issue?
