### ISSUE TITLE
manylinux builds?

### ISSUE THREAD

**Issue by hrw** [tensorflow/io#1507]
Now you are using python-3.x-slim docker images to build. But they are x86-64 only which makes builds on non-x86_64 more complicated.

Tensorflow is buildable in manylinux2014 so would be nice to be able to build tensorflow/io there as well.

**Comment by hrw** [comment]
Nevermind. toolchain in manylinux2014 image lacks "__cxa_throw_bad_array_new_length" and "std::__throw_out_of_range_fmt" functions :(

**Comment by hrw** [comment]
```     
 export BAZEL_LINKLIBS=-l%:libstdc++.a
```

to the rescue ;D

**Comment by hrw** [comment]
```
[root@jagular ansible]# auditwheel repair dist/tensorflow_io-0.20.0-cp39-cp39-linux_aarch64.whl 
INFO:auditwheel.main_repair:Repairing tensorflow_io-0.20.0-cp39-cp39-linux_aarch64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 8, in <module>
    sys.exit(main())
  File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main.py", line 51, in main
    rval = args.func(args, p)
  File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main_repair.py", line 123, in execute
    out_wheel = repair_wheel(args.WHEEL_FILE,
  File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/repair.py", line 67, in repair_wheel
    raise ValueError(('Cannot repair wheel, because required '
ValueError: Cannot repair wheel, because required library "libtensorflow_framework.so.2" could not be located
```

Any suggestions?

**Comment by hrw** [comment]
Found https://github.com/tensorflow/io/commit/02dcf4a hack.

**Comment by hrw** [comment]
And built: https://snapshots.linaro.org/ldcg/python-cache/tensorflow-io-gcs-filesystem/
