### ISSUE TITLE
tf.image.resize() behaves differently when wrapped in a tf.data.Dataset.map()

### ISSUE THREAD

**Issue by goncinious** [tensorflow/io#1534]
`tf.image.resize()` gives different results if used as is (plain) or if wrapped in a `tf.data.Dataset.map()`, however, I except the output to be the same in both cases. The different results are shown in the output of the snipped below.

Specifically, this issue seems related to the specific interpolation method `tf.image.ResizeMethod.BILINEAR` (default) with uses [`tensorflow.python.ops.gen_image_ops.resize_bilinear`](https://github.com/tensorflow/tensorflow/blob/v2.6.0/tensorflow/python/ops/image_ops_impl.py#L1700) under-the-hood. Changing the interp method (e.g. to `tf.image.ResizeMethod.BICUBIC`, or setting bilinear + `antialias=True`, which uses a different method) no longer show any differences.

Environment:
- Tensorflow 2.6.0
- Python 3.8.6

Reproducible script:
```
import tensorflow as tf
import numpy as np
from PIL import Image

print(tf.__version__)

@tf.function
def tf_read_and_resize_image(filename):
    image_string = tf.io.read_file(filename)
    image = tf.image.decode_jpeg(image_string, channels=3)
    image=tf.cast(image, tf.float32)
    image = tf.image.resize(image, (224, 224), method=tf.image.ResizeMethod.BILINEAR)
    return image

# create random uint8 image
np.random.seed(42)
im = np.random.randint(low=0, high=255, size=(100, 100, 3), dtype=np.uint8)
im_filename = "/tmp/test_image.jpg"
im = Image.fromarray(im).save(im_filename)

# plain function
plain_tensor = tf_read_and_resize_image(im_filename)

# wrapped in tf.data map()
ds = tf.data.Dataset.from_tensor_slices([im_filename])
ds = ds.map(tf_read_and_resize_image)
ds_tensor = next(ds.as_numpy_iterator())

assert plain_tensor.dtype == ds_tensor.dtype == "float32"
assert plain_tensor.shape == ds_tensor.shape == (224, 224, 3)
np.testing.assert_array_equal(plain_tensor, ds_tensor) # fails with ~11% diff.
```

Output: 
```
(tf_issue) root@f1f0235af85c:/srv/2D3Dreg/deeplearning# python test.py 
2.6.0
2021-09-28 14:10:08.987749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.997055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.997667: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.998427: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-28 14:10:08.999018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:08.999644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.000204: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.584861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.585487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.586072: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-28 14:10:09.586636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13666 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5
2021-09-28 14:10:09.596141: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    np.testing.assert_array_equal(input_tensor_read, ds_read) # fails with ~11% diff.
  File "/srv/2D3Dreg/deeplearning/tf_issue/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 930, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/srv/2D3Dreg/deeplearning/tf_issue/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 16381 / 150528 (10.9%)
Max absolute difference: 0.00051498
Max relative difference: 1.0005011e-05
 x: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
 y: array([[[164.      , 208.      , 131.      ],
        [154.83928 , 198.83928 , 124.55357 ],
        [130.73215 , 174.73215 , 107.58929 ],...
```

**Comment by goncinious** [comment]
I'll post this issue on tensorflow main repo.
