### ISSUE TITLE
Cannot install Tensorflow.io on Mac M1

### ISSUE THREAD

**Issue by sconiac** [tensorflow/io#1625]
Hi Im trying to use Tensorflow.io while im learning object detection with this tutorial: https://www.youtube.com/watch?v=yqkISICHH-U&t=9352s and while im training my model I noticed an import of Tensorflow.io but I cannot install it. I try "pip install tenorflow.io" but I get error like: 
ERROR: Could not find a version that satisfies the requirement tensorflow.io (from versions: none)
ERROR: No matching distribution found for tensorflow.io

**Comment by ZaibanAli** [comment]
I am having the same issue. Did you found something related to this?

**Comment by kvignesh1420** [comment]
you can install using `pip install tensorflow-io`. However, please note that the following are different:
```
import tensorflow as tf
# use tf.io.gfile.listdir(...)
import tensorflow_io as tfio
# use tfio.IODataset.from_audio(...)
```

**Comment by ZaibanAli** [comment]
After running `pip install tensorflow-io` I get this error:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-io (from versions: none)
ERROR: No matching distribution found for tensorflow-io
```

**Comment by kvignesh1420** [comment]
@ZaibanAli Since GitHub actions don't support M1 mac based runner environments, we couldn't auto build and publish the `tensorflow-io` wheels to PyPI for M1 devices. We are working on alternatives to add the support!

**Comment by ZaibanAli** [comment]
I tried to build io myself using `python3 setup.py -q bdist_wheel` but it gave me this error.

`Project: tensorflow-io
Exclude: ['tests', 'tests.*', 'tensorflow_io_gcs_filesystem', 'tensorflow_io_gcs_filesystem.*']
Install Requires: ['tensorflow-io-gcs-filesystem==0.24.0']
Project Rootpath: tensorflow_io
Traceback (most recent call last):
  File "setup.py", line 138, in <module>
    setuptools.setup(
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/Users/zaiban.ali/miniforge3/envs/test0/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_0_arm64')`

**Comment by aelmrabe** [comment]
Hi @kvignesh1420 , I have same issue, I can't install tensorflow-io on Mac m1. Till now, I am only able to install tensorflow-macos and tensorflow-metal successfully. Do you have any update or clue on the issue ? Is it possible to build the tensorflow-io source code from my machine  Mac m1 ? If yes which tensorflow-io version I have to take ? 

Here the version of tensorflow-deps installed in my machine.

**tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow-macos        2.8.0
tensorflow-metal        0.3.0**

We really appreciate your help. Many thanks.

**Comment by loyio** [comment]
same issues

**Comment by invoxiaehu** [comment]
same issue

**Comment by sconiac** [comment]
Ive fix it somehow, i think using wheel help. and then i need to manually change in files downloaded from the tutorial _tensorflow.io_ to _tensorflow-io_. It works for me but i'm not sure how exactly i fix it 😄

**Comment by ZaibanAli** [comment]
@sconiac can you please tell us in more detail how you did it? I am stuck with this for more than 2 weeks.

**Comment by sconiac** [comment]
I remove my old project, so I create new one by following this tutorial: [https://developer.apple.com/metal/tensorflow-plugin/](url). Then I type:
`$ git clone https://github.com/tensorflow/io.git`
`$ cd io`
`$ python3 setup.py -q bdist_wheel`
`Project: tensorflow-io
Exclude: ['tests', 'tests.*', 'tensorflow_io_gcs_filesystem', 'tensorflow_io_gcs_filesystem.*']
Install Requires: ['tensorflow-io-gcs-filesystem==0.24.0']
Project Rootpath: tensorflow_io
/Users/olivierskonieczny/miniforge3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(` 
(There I get a warning but importing at the end work (also with some weird warnings :) ))

`$ python3 -m pip install --no-deps dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl`

And last I check if every thing works by:
`$ python3`
>>> import tensorflow_io as tfio
>>> print(tfio.__version__)
0.24.0

**Comment by ZaibanAli** [comment]
@sconiac thank you for explaining what you did. I already reached this point but the part where it throws a dynamic library error is the critical one and it is required by Tensorflow object detection api.

**Comment by sconiac** [comment]
Oh, sorry. I didn't notice that, but I'm afraid I don't know how to fix your issue. On my Mac every think works fine, even training my own model. I think you can try old fixing method just reinstall everything you can and that may help.

**Comment by dvaldivia** [comment]
Seems like @sconiac steps only works for `MacOS 11` not for `macOS 12` (Monterey)

**Comment by dusskapark** [comment]
same issue

**Comment by AntonMaj** [comment]
also got the same issue

**Comment by lhayhurst** [comment]
Came here to say, same issue :-)

**Comment by wadinj** [comment]
Same issue aswell

**Comment by natehust** [comment]
same issue as well

**Comment by guokr233** [comment]
same issue : )

**Comment by gabijazdan** [comment]
Same issue, macOS 12 specifically.

**Comment by GeoffreyBrunet** [comment]
Same on Mac OS 12 Monterey, with this error:
```
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```
Any news about compatibility with Apple Silicon please ?

**Comment by yaminocellist** [comment]
Similar issue on MacOs Monterey 12.3.1.
I tried every method I can find but it still throws:

ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow) (from versions: none)
ERROR: No matching distribution found for tensorflow-io-gcs-filesystem>=0.23.1

**Comment by doncarlos999** [comment]
Same issue (macosx12 m1):
```
AssertionError: would build wheel with unsupported tag ('cp39', 'cp39', 'macosx_11_0_arm64')
```

**Comment by maxmacstn** [comment]
Same issue on M1 Pro

**Comment by sriramk146** [comment]
I recently updated my mac to OS 12.3.1 (M1), I am also facing same issue on installing tensorflow-io. kindly share any, if it can be fixed.

**Comment by giacomomiolo** [comment]
Same issue as well

**Comment by alexpotv** [comment]
I am also facing the same issue on MacOS 12.3.1, on an M1 Pro 2021 MacBook Pro!

**Comment by elia-secchi** [comment]
Same problem here!

**Comment by doncarlos999** [comment]
Putting this here in case anybody else runs into the same issue I had with using conda.
I finally got this working by ignoring the instructions [here](https://developer.apple.com/metal/tensorflow-plugin/). And doing the following:
```
cd 
python3 -m venv .tensorflow
source ~/.tensorflow/bin/activate
brew install hdf5
export CPATH="/opt/homebrew/include/"
export HDF5_DIR=/opt/homebrew/
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
git clone https://github.com/tensorflow/io.git
cd io
python setup.py -q bdist_wheel --project tensorflow_io_gcs_filesystem
pip install --no-deps dist/tensorflow_io_gcs_filesystem-0.25.0-cp39-cp39-macosx_12_0_arm64.whl
python setup.py -q bdist_wheel
pip install --no-deps dist/tensorflow_io-0.25.0-cp39-cp39-macosx_12_0_arm64.whl
```
There may be other system requirements that need to be installed through brew that I already had installed. YMMV.

**Comment by doncarlos999** [comment]
I am on macos 12.3

**Comment by sun1638650145** [comment]
First of all, thank you very much for your help. Although the build can be successful, there is no `libtensorflow_io.so` which makes it practically unavailable.

**Comment by doncarlos999** [comment]
I only needed `tfio` for running `tfio.experimental.color.rgb_to_lab` within the [TensorFlow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection) and my above method was enough for that.

Hopefully an official fix with full functionality will be available soon.

**Comment by leochoo** [comment]
Same issue. I get the following message.
My build fails.

```
$ git clone https://github.com/tensorflow/io.git
$ cd io
$ python setup.py -q bdist_wheel

Project: tensorflow-io
Exclude: ['tests', 'tests.*', 'tensorflow_io_gcs_filesystem', 'tensorflow_io_gcs_filesystem.*']
Install Requires: ['tensorflow-io-gcs-filesystem==0.26.0']
Project Rootpath: tensorflow_io
/opt/homebrew/Caskroom/mambaforge/base/envs/tf2/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
warning: install_lib: 'build/lib.macosx-11.0-arm64-cpython-39' does not exist -- no Python modules to install

```

**Comment by orderer0001** [comment]
> 

I followed your method and got the error:
ERROR: tensorflow_io_gcs_filesystem-0.25.0-cp39-cp39-macosx_12_0_arm64.whl is not a supported wheel on this platform.

**Comment by jvgalvin** [comment]
I'm facing the same issue as well. Getting the same errors when using the workarounds, too.

**Comment by Elisha-Veve** [comment]
Tried every method here and still getting errors. As people have been having this issue since February 6, was anyone able to resolve it or they just used a different OS altogether

**Comment by ilivid** [comment]
same issue

**Comment by winklerjustine** [comment]
same!

**Comment by wadinj** [comment]
Hi @kvignesh1420, I think M1 Mac from Github actions is now available - see https://github.com/actions/runner/issues/805.

Any idea if we can build a wheel for ARM target ?

Thanks

**Comment by wadinj** [comment]
Hi @kvignesh1420 - any change to take a look on it ? 

Thanks a lot 🥇

**Comment by sergiomujica** [comment]
nothing yet?

**Comment by kvignesh1420** [comment]
Will be looking into this soon. Meanwhile, contributions are welcome if anyone is already working on this.

**Comment by teocasse** [comment]
Is tensorflow-io using self-hosted runners? Because if you are using github-hosted runners instead, my understanding is that the VMs for it are on the roadmap but without a release date yet. The pre-release linked above is only for self-hosted runners.

**Comment by keysmusician** [comment]
Same issue on a MacBook Air (M1, 2020), macOS Monterey 12.5. Thank you to those working on it!

**Comment by krunduev** [comment]
The same on macOS Monterey 12.1, MacBook Air  M1, 2020

**Comment by tgsmith61591** [comment]
@kvignesh1420 for those interested in trying to build `libtensorflow_io.so` on Apple silicon, can you point us to documentation on the build? Several other `tensorflow` ecosystem projects have a `build_pip_package` bazel target

**Comment by ankitvgupta** [comment]
Hi @kvignesh1420, could you clarify what contributions you were looking for exactly? I tried the above solutions, i.e. to clone the repo, run `setup.py` followed by

```
pip install --no-deps dist/tensorflow_io_gcs_filesystem-0.26.0-cp39-cp39-macosx_12_0_arm64.whl
pip install --no-deps dist/tensorflow_io-0.26.0-cp39-cp39-macosx_12_0_arm64.whl
```

and that appears to install tensorflow IO (I can import it now), but I'm still not getting some core functionality. 

For example, when I try to create a TFRecordDataset with s3 paths for the filenames, I get 
```
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented
```

Even if the official M1 arm automatic builds aren't ready, is there a workaround you know of to get this to work manually?

**Comment by mikgross** [comment]
Same issue here. Any release planned date? Thanks 👍

**Comment by dvaldivia** [comment]
I think part of the problem is the dependency on bazel and bazel not building things on M1, perhaps an alternative build strategy should be introduced meanwhile?

**Comment by wadinj** [comment]
Thanks to @yongtang  #1298 1625 ! We now have a aarch wheel available to pypi !

**Comment by ankitvgupta** [comment]
Just wanted to check in on this @kvignesh1420 - is there anything we can do to help with this? This is currently the last thing remaining for me to move most of my tensorflow development to my Mac natively, and I'm eager to do so.

**Comment by dvaldivia** [comment]
so @nicholasjng made some progress on https://github.com/google/ml-metadata/issues/143#issuecomment-1295234578 getting another similar project to compile by updating the bazel dependencies, perhaps when he submits a PR we can copy some of the improvements

**Comment by yingding** [comment]
same issue, would love to use `pip install tensorflow-io==0.27.0` with `tensorflow-macos==2.10.0` and python 3.10

**Comment by maltequast** [comment]
@sconiac solutions works on macOS 13.0.

**Comment by ankitvgupta** [comment]
thanks @dvaldivia - any idea if their PR (https://github.com/google/ml-metadata/pull/166) is mappable to here? I'm not much of a bazel expert but I could poke around.

**Comment by piaoziyue** [comment]
same issue

**Comment by darrenrahnemoon** [comment]
same issue  🏳️

**Comment by nmatare** [comment]
bump on issue

**Comment by qhuang0411** [comment]
same issue

**Comment by SuperHao-Wu** [comment]
same issue, any updates?

**Comment by surferfelix** [comment]
same issue

**Comment by AnasAr96** [comment]
> I remove my old project, so I create new one by following this tutorial: [https://developer.apple.com/metal/tensorflow-plugin/](url). Then I type: `$ git clone https://github.com/tensorflow/io.git` `$ cd io` `$ python3 setup.py -q bdist_wheel` `Project: tensorflow-io Exclude: ['tests', 'tests.*', 'tensorflow_io_gcs_filesystem', 'tensorflow_io_gcs_filesystem.*'] Install Requires: ['tensorflow-io-gcs-filesystem==0.24.0'] Project Rootpath: tensorflow_io /Users/olivierskonieczny/miniforge3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn(` (There I get a warning but importing at the end work (also with some weird warnings :) ))
> 
> `$ python3 -m pip install --no-deps dist/tensorflow_io-0.24.0-cp39-cp39-macosx_11_0_arm64.whl`
> 
> And last I check if every thing works by: `$ python3` `>>> import tensorflow_io as tfio` (its part that throw some error ) `>>> print(tfio.__version__)` `0.24.0`
> 
> Hope all works,

Worked for me after giving the absolut path to the whl. filed

Thank you

**Comment by dusskapark** [comment]
@AnasAr96 , 

I have tried to follow your steps. I successfully passed `tensorflow_io` installation huddle though, I met another error below. Could you please share your trouble shooting experience for all of us?

```
ERROR: Cannot install object-detection because these package versions have conflicting dependencies.

The conflict is caused by:
    tf-models-official 2.11.2 depends on tensorflow-text~=2.11.0
    tf-models-official 2.11.0 depends on opencv-python-headless==4.5.2.52
    tf-models-official 2.10.1 depends on tensorflow-text~=2.10.0
    tf-models-official 2.10.0 depends on opencv-python-headless==4.5.2.52
    tf-models-official 2.9.2 depends on tensorflow~=2.9.0
    tf-models-official 2.9.1 depends on tensorflow~=2.9.0
    tf-models-official 2.9.0 depends on tensorflow~=2.9.0
    tf-models-official 2.8.0 depends on tensorflow~=2.8.0
    tf-models-official 2.7.2 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.1 depends on tensorflow-text>=2.4.0
    tf-models-official 2.7.0 depends on tensorflow>=2.7.0
    tf-models-official 2.6.1 depends on tensorflow-text>=2.6.0
    tf-models-official 2.6.0 depends on tensorflow>=2.5.0
    tf-models-official 2.5.1 depends on tensorflow>=2.5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by AnasAr96** [comment]
@dusskapark ,
you can view it on 

https://github.com/B1tstorm/ki-anwendung_object-detection/issues/13

**Comment by crueda** [comment]
python3 -m pip install tensorflow-macos
python3 -m pip install tensorflow-metal

**Comment by AnasAr96** [comment]
> python3 -m pip install tensorflow-macos
> python3 -m pip install tensorflow-metal

It is about Tensorflow-io not only Tensorflow

**Comment by MATTYGILO** [comment]
Still occurring, any solutions?

**Comment by lakhman** [comment]
[The comment/link from AnasAr96](https://github.com/B1tstorm/customized_object_detection_system/issues/13) worked for me for the object-detection model, I've included it below (Thanks @AnasAr96):

> After a long research I found out that object-detection from tf2 is not compatible on M1 Macs.
> 
> but the old version of tf1 would also work without problems.
> 
> change your installation to be like:
> - From within TensorFlow/models/research/
> 
> cp object_detection/packages/tf1/setup.py .
> python -m pip install . --no-deps

So try using tf1:
```
# Ensure you're in tensorflow/models/research directory
cp object_detection/packages/tf1/setup.py .
python -m pip install . --no-deps
```

**Comment by SidharthArya** [comment]
I guess one solution for now is to
```
git clone https://github.com/tensorflow/io
cd io
python setup.py build
python setup.py install
```

**Comment by ankitvgupta** [comment]
When I run the above and then `import tensorflow_io` on my M1 Mac, I now get: 

```
 UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so,
```

is this the expected behavior? best I can tell the above solutions are not actually installing tensorflow_io on M1 mac yet.

**Comment by AndrewKovalenko** [comment]
With the resolution above it seems that some functionality is available and some is not. 
After 
```
git clone https://github.com/tensorflow/io
cd io
python setup.py build
python setup.py install
```
`import tensorflow_io as tfio` works fine but attempt to use `AudioIOTensor` crashes:

```
audio = tfio.audio.AudioIOTensor('gs://cloud-samples-tests/speech/brooklyn.flac')

NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ...
```

**Comment by xplfly** [comment]
MacBook Air (M1, 2020) version:12.3.1 (21E258)
Here are the steps to resolve this issue:
`
git clone https://github.com/tensorflow/io
cd io
python setup.py bdist_wheel
cd dist
python -m pip install --no-deps tensorflow_io-0.32.0-cp310-cp310-macosx_11_0_arm64.whl
`

**Comment by gil-mark** [comment]
I'm also getting the `unable to load libtensorflow_io_plugins.so` error that some others have reported above, any idea how to fix this?

**Comment by sun1638650145** [comment]
Now, `io` can be built perfectly on Apple silicon. If anyone needs it, you can find the tutorial [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/io/io.md). I hope it can be helpful to everyone.

**Comment by yingding** [comment]
I am able to install it directly with `pip install tensorflow-io tensorflow==2.13.0 tensorflow-metal==1.0.1`.
Now when I run
```python
import tensorflow_io as tfio
audio = tfio.audio.AudioIOTensor('gs://cloud-samples-tests/speech/brooklyn.flac')
```
I got the error `no attribute 'io_audio_readable_init' for `AudioIOTensor`. Any idea what went wrong?
```console
File [~/VENV/tfio3.10/lib/python3.10/site-packages/tensorflow_io/python/ops/audio_ops.py:671](https://file+.vscode-resource.vscode-cdn.net/Users/yingding/VCS/github/ml/tf-every-day/08Audio/~/VENV/tfio3.10/lib/python3.10/site-packages/tensorflow_io/python/ops/audio_ops.py:671), in AudioIOTensor.__init__(self, filename, dtype)
    669 if not tf.executing_eagerly():
    670     assert dtype is not None, "dtype must be provided in graph mode"
--> 671 resource = core_ops.io_audio_readable_init(filename)
    672 if tf.executing_eagerly():
    673     shape, dtype, rate = core_ops.io_audio_readable_spec(resource)

File [~/VENV/tfio3.10/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:88](https://file+.vscode-resource.vscode-cdn.net/Users/yingding/VCS/github/ml/tf-every-day/08Audio/~/VENV/tfio3.10/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:88), in LazyLoader.__getattr__(self, attrb)
     87 def __getattr__(self, attrb):
---> 88     return getattr(self._load(), attrb)

AttributeError: module '56c055b4afaba95af0256db7c72edd0d967e1981' has no attribute 'io_audio_readable_init'
```

**Comment by AndrewKovalenko** [comment]
@sun1638650145 
running `bazel build -s --verbose_failures $BAZEL_OPTIMIZATION //tensorflow_io/... //tensorflow_io_gcs_filesystem/...` fails with `ERROR: Analysis of target '//tensorflow_io/core:audio_video_ops' failed; build aborted:`

earlier it fails with:
```
ERROR: /private/var/tmp/_bazel_labtop/88c3e6e6a1cefdee4288d9051d766a45/external/build_bazel_rules_swift_local_config/BUILD:9:22: in xcode_swift_toolchain rule @build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_labtop/88c3e6e6a1cefdee4288d9051d766a45/external/build_bazel_rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 708, column 34, in _xcode_swift_toolchain_impl
		if _is_xcode_at_least_version(xcode_config, "11.0"):
	File "/private/var/tmp/_bazel_labtop/88c3e6e6a1cefdee4288d9051d766a45/external/build_bazel_rules_swift/swift/internal/xcode_swift_toolchain.bzl", line 586, column 13, in _is_xcode_at_least_version
		fail("Could not determine Xcode version at all. This likely means " +
Error in fail: Could not determine Xcode version at all. This likely means Xcode isn't available; if you think this is a mistake, please file an issue.
ERROR: /private/var/tmp/_bazel_labtop/88c3e6e6a1cefdee4288d9051d766a45/external/build_bazel_rules_swift_local_config/BUILD:9:22: Analysis of target '@build_bazel_rules_swift_local_config//:toolchain' failed
```

XCode: Version 14.3.1 (14E300c)
MacOs: Version 13.4

**Comment by AndrewKovalenko** [comment]
@sun1638650145 I followed your guide and installed locally built **tensorflow-io**
```
tfio.__version__ // prints '0.34.0'
```
however I still get `unable to open file: libtensorflow_io.so, from paths: ['/Users/labtop/miniconda3/envs/tensorflow-2-13/lib/python3.11/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']` if I try to run `audio = tfio.audio.AudioIOTensor('gs://cloud-samples-tests/speech/brooklyn.flac')`

**Comment by sid-kap** [comment]
FYI there is an Apple Silicon wheel for tensorflow-io 0.34.0 on pypi now
https://pypi.org/project/tensorflow-io/#files

**Comment by sid-kap** [comment]
FYI there is an Apple Silicon wheel for tensorflow-io 0.34.0 on pypi now
https://pypi.org/project/tensorflow-io/#files

**Comment by sun1638650145** [comment]
@AndrewKovalenko This error appears to be caused by a failure to successfully compile `libtensorflow_io.so`. You can try recompiling it with `sudo`.

**Comment by sun1638650145** [comment]
@yingding I can reproduce this error as well. It seems unrelated to the compilation/build process. You should consider opening a new issue for this problem.

**Comment by yingding** [comment]
@sun1638650145 Thanks for linking the issue https://github.com/tensorflow/io/issues/1855#issue-1891614754, which might be caused by the same root cause of mine. I just opened issue https://github.com/tensorflow/io/issues/1859 to track progress.

Are the other features of tfio 0.34.0 usable on M1 besides the AudioIOTensor? or do I need to build manually as workaround.

**Comment by eashvere** [comment]
This worked for me on my M1 Mac (Sonoma) with XCode 15 with Tensorflow 2.13 (Python 3.10)

> Now, `io` can be built perfectly on Apple silicon. If anyone needs it, you can find the tutorial [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/io/io.md?rgh-link-date=2023-09-09T04%3A17%3A58Z). I hope it can be helpful to everyone.

Although, instead of checking out 0.34, I had to make some adjustments to the build process: [https://github.com/eashvere/io](https://github.com/eashvere/io)
- Re-adding audio_video_ops to compile on arm64
- Making sure the swift library compiled to arm64
- adding a flag to re-enable unary and binary functions (XCode 15 specific)

Didn't test on other devices, older XCodes and other versions of Python.

**Comment by sam-goodwin** [comment]
There are ARM macos runners now, is it possible to publish now? Lot of people in this thread affected by this problem.

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by yackermann** [comment]
Started discussion on the forum https://discuss.ai.google.dev/t/io-lib-is-broken-on-apple-silicon-attributeerror-module-has-no-attribute-io-audio-decode-wav/57926
