### ISSUE TITLE
unable to open file: libtensorflow_io.so in Windows 11

### ISSUE THREAD

**Issue by chowdhurySudip** [tensorflow/io#1783]
OS: Windows 11
TF Version: 2.10.1
TFIO Version: 0.31.0

While using `tfio.audio.resample(waveform, rate_in=sr, rate_out=SAMPLE_RATE)`, I am getting following error.

Traceback (most recent call last):
  File "C:\Users\sudip\Desktop\workspace\audio\tf_pipeline\audio.py", line 12, in <module>
    waveform = tfio.audio.resample(waveform, rate_in=sr, rate_out=SAMPLE_RATE)
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\audio_ops.py", line 462, in resample
    value = tf.vectorized_map(f, input)
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 565, in vectorized_map
    return pfor(
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow\python\ops\parallel_for\control_flow_ops.py", line 214, in pfor
    outputs = f()
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\sudip\AppData\Local\Temp\__autograph_generated_file8xamt8f8.py", line 17, in tf__f
    retval_ = ag__.converted_call(ag__.ld(_pfor_impl), (ag__.ld(loop_fn), ag__.ld(iters)), dict(fallback_to_while_loop=ag__.ld(fallback_to_while_loop), parallel_iterations=ag__.ld(parallel_iterations), warn=ag__.ld(warn)), fscope)
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\audio_ops.py", line 458, in f
    return core_ops.io_audio_resample(
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 88, in __getattr__
    return getattr(self._load(), attrb)
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 84, in _load
    self._mod = _load_library(self._library)
  File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 69, in _load_library
    raise NotImplementedError(
NotImplementedError: in user code:

    File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\audio_ops.py", line 458, in f
        return core_ops.io_audio_resample(
    File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 88, in __getattr__
        return getattr(self._load(), attrb)
    File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 84, in _load
        self._mod = _load_library(self._library)
    File "C:\Users\sudip\miniconda3\envs\tf\lib\site-packages\tensorflow_io\python\ops\__init__.py", line 69, in _load_library
        raise NotImplementedError(

    NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['C:\\Users\\sudip\\miniconda3\\envs\\tf\\lib\\site-packages\\tensorflow_io\\python\\ops\\libtensorflow_io.so']
    caused by: ['C:\\Users\\sudip\\miniconda3\\envs\\tf\\lib\\site-packages\\tensorflow_io\\python\\ops\\libtensorflow_io.so not found']

Although, I found the `libtensorflow_io.so` file in `C:\Users\sudip\miniconda3\envs\tf\Lib\site-packages\tensorflow_io\python\ops` folder.

**Comment by akudilcz** [comment]
Having the same issue here.

OS: Windows 11
TF Version: 2.10.1
TFIO Version: 0.31.0

![image](https://user-images.githubusercontent.com/6821222/230250747-81a6b60b-176e-4a52-a463-637aebfc1191.png)

**Comment by jvssoft** [comment]
Having the same issue here

**Comment by digidax** [comment]
Same problem here:
Alma Linux 9.2
Python 3.9.16
Tensorflow 2.14.0
Tensorflow-io 0.34.0

`def load_wav_16k_mono(filename):
    file_contents = tf.io.read_file(filename)
    wav, sample_rate = tf.audio.decode_wav(
          file_contents,
          desired_channels=1)
    wav = tf.squeeze(wav, axis=-1)
    sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
    return wav
`
  File "/root/ki/vinyl.py", line 31, in load_wav_16k_mono
    wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/audio_ops.py", line 469, in resample
    value = tf.vectorized_map(f, input)
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 578, in vectorized_map
    return pfor(
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 228, in pfor
    outputs = f()
  File "/usr/local/lib64/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file_8gv5gf4.py", line 17, in tf__f
    retval_ = ag__.converted_call(ag__.ld(_pfor_impl), (ag__.ld(loop_fn), ag__.ld(iters)), dict(fallback_to_while_loop=ag__.ld(fallback_to_while_loop), parallel_iterations=ag__.ld(parallel_iterations), warn=ag__.ld(warn)), fscope)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/audio_ops.py", line 465, in f
    return core_ops.io_audio_resample(
  File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 88, in __getattr__
    return getattr(self._load(), attrb)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 84, in _load
    self._mod = _load_library(self._library)
  File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 69, in _load_library
    raise NotImplementedError(
NotImplementedError: in user code:

    File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/audio_ops.py", line 465, in f
        return core_ops.io_audio_resample(
    File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 88, in __getattr__
        return getattr(self._load(), attrb)
    File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 84, in _load
        self._mod = _load_library(self._library)
    File "/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/__init__.py", line 69, in _load_library
        raise NotImplementedError(

    NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
    caused by: ['/usr/local/lib/python3.9/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']

**Comment by aad1m1** [comment]
Having the same issue.

**Comment by rutwik1440** [comment]
I am also facing same issue.

**Comment by alokprasad-mrvl** [comment]
same issue
