### ISSUE TITLE
Support for Parquet byte array (binary) column type

### ISSUE THREAD

**Issue by megaserg** [tensorflow/io#532]
Is it currently possible to read Parquet dataset with a byte array (binary) column?

I'm using `tensorflow_io_nightly-0.9.0.dev1911-cp27-cp27mu-manylinux2010_x86_64.whl` and Tensorflow 2.0. I'm constructing dataset like this:
```
dataset = tensorflow_io.IODataset.from_parquet(
            filename,
            ["int_column", "binary_column"])
```
and getting:
```
2019-10-09 01:17:39.127345: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at io_interface.h:231 : Invalid argument: invalid data type: 6
2019-10-09 01:17:39.127425: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Invalid argument: {{function_node __inference_Dataset_map_<lambda>_128}} invalid data type: 6
	 [[{{node ParquetReadableRead}}]]
Traceback (most recent call last):
  File "framework/dataset/parquetrecord.py", line 131, in <module>
    main()
  File "framework/dataset/parquetrecord.py", line 117, in main
    for row in dataset.prefetch(10):
  File "/home/megaserg/.local/lib/python2.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 666, in next
    return self._next_internal()
  File "/home/megaserg/.local/lib/python2.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/home/megaserg/.local/lib/python2.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2673, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_128}} invalid data type: 6
	 [[{{node ParquetReadableRead}}]] [Op:IteratorGetNextSync]
```

Thanks!

**Comment by yongtang** [comment]
@megaserg Added a PR #533 for BinaryArray and FixedLenBinaryArray support.
