### ISSUE TITLE
Support decode_json to decode json into Tensor

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#692]
This is a feature request (from gitter channel) to add `decode_json` so that it is possible to convert json strings such as below:
```
{
    "Foo": 208.82240295410156,
    "Bar": "93",
    "Background": "~/0109.jpg",
    "Focal Length": 36.9439697265625,
    "Location": [ 7.8685874938964844, -4.7373886108398438, -0.038147926330566406 ],
    "Rotation": [ -4.592592716217041, -4.4698805809020996, -6.9197754859924316 ]
}
```

into Tensors.

The method `decode_json` could be efficiently combined with `tf.data` pipeline so that the following is possible:
```
dataset = tf.data.Dataset.from_tensor_slices(["file_0.json", "file_1.json", "file_2.json"])
dataset = dataset.map(tf.io.read_file)
dataset = dataset.map(lambda e: decode_json(e))
...
# feed dataset to tf.keras directly:
model.fit(dataset)
```

/cc @noahtren

**Comment by noahtren** [comment]
Is this what `tfio.IOTensor.from_json` should be doing? I'm running this function on a JSON file and get the following error.
```
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    for example in ds:
  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "~/anaconda3/envs/tf2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mode
    executor_new.wait()
  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.UnknownError: InvalidArgumentError: unable to read table: Invalid: JSON parse error: Missing a comma or '}' after an object member. [Op:IO>JSONReadableInit]
Traceback (most recent call last):

  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 234, in __call__
    return func(device, token, args)

  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/script_ops.py", line 123, in __call__
    ret = self._func(*args)

  File "main.py", line 29, in load_func
    json_data = load_json(json_path)

  File "main.py", line 24, in load_json
    return tfio.IOTensor.from_json(json_path)

  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_io/core/python/ops/io_tensor.py", line 280, in from_json
    filename, mode=kwargs.get('mode', None), internal=True)

  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_io/core/python/ops/json_io_tensor_ops.py", line 42, in __init__
    shared_name="%s/%s" % (filename, uuid.uuid4().hex))

  File "<string>", line 6479, in io_json_readable_init

  File "<string>", line 6537, in io_json_readable_init_eager_fallback

  File "~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

tensorflow.python.framework.errors_impl.InvalidArgumentError: unable to read table: Invalid: JSON parse error: Missing a comma or '}' after an object member. [Op:IO>JSONReadableInit]
```

Not sure why it's complaining about the JSON file format. Is there a specific table format it's looking for?

**Comment by yongtang** [comment]
@noahtren There are two modes, one is the "records" mode, another is the "ndjson" mode. Can you share the content of your JSON file example?

**Comment by noahtren** [comment]
It's comparable to the sample above. Some keys map to strings, some floats, and some arrays.

**Comment by noahtren** [comment]
The above error was with the nightly version of tfio. Getting different errors with the current stable version unfortunately:

Loading it in `records` mode is giving me a segmentation fault

Loading it in `ndjson` mode gives me the following error
```
external/arrow/cpp/src/arrow/json/reader.cc:93:  Check failed: (string_view(*next_partial).find_first_not_of(" \t\n\r")) == (string_view::npos) external/arrow/cpp/src/arrow/json/reader.ccexternal/arrow/cpp/src/arrow/json/reader.cc
::93: 93:  Check failed: (string_view(*next_partial).find_first_not_of(" \t\n\r")) == (string_view::npos) 
Aborted (core dumped)
```

**Comment by yongtang** [comment]
@noahtren JSON dataset expect a repeated records of same structure, either in ndjson format, or in a JSON array. So it may not be a good fit for what you are looking for if your JSON data is `one` record. 

That is the `decode_json` tries to solve. Let me take a look and get back to you shortly.

**Comment by noahtren** [comment]
Ah got it, thanks!

`decode_json` would produce a dict of tensors, right? Where each value of the JSON file is converted to a suitable Tensor? I'm thinking of it as doing something like calling `tf.convert_to_tensor` on each value in the JSON file and returning a tensor dictionary.

**Comment by kyprifog** [comment]
@yongtang does decode_json support nested JSON?  I tried to make the SPEC document be nested itself but that doesn't seem to do the trick.
