### ISSUE TITLE
Support install from source with `pip install -e .`

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/io#707]
I forked the project and then in the directory tried to install the package with `pip install -e .`.

I got the following error:
```
ERROR: Command errored out with exit status 1:
     command: /home/zaccharie/workspace/io/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zaccharie/workspace/io/setup.py'"'"'; __file__='"'"'/home/zaccharie/workspace/io/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/zaccharie/workspace/io/
    Complete output (23 lines):
    setup.py - project = 'tensorflow-io'
    setup.py - package = 'tensorflow>=2.1.0rc1'
    setup.py - version = '0.11.0'
    setup.py - create /tmp/tmpwo86ujmd and copy tensorflow_io
    setup.py - create /tmp/tmpwo86ujmd/MANIFEST.in
    setup.py - create /tmp/tmpwo86ujmd/setup.py with required = 'tensorflow>=2.1.0rc1', project_name = 'tensorflow-io' and __version__ = 0.11.0
    setup.py - run sandbox.run_setup /tmp/tmpwo86ujmd/setup.py ['egg_info']
    running egg_info
    creating tensorflow_io.egg-info
    writing tensorflow_io.egg-info/PKG-INFO
    writing dependency_links to tensorflow_io.egg-info/dependency_links.txt
    writing requirements to tensorflow_io.egg-info/requires.txt
    writing top-level names to tensorflow_io.egg-info/top_level.txt
    writing manifest file 'tensorflow_io.egg-info/SOURCES.txt'
    reading manifest file 'tensorflow_io.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.so' under directory 'tensorflow_io'
    writing manifest file 'tensorflow_io.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/zaccharie/workspace/io/setup.py", line 275, in <module>
        for f in os.listdir(os.path.join(rootpath, "dist")):
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwo86ujmd/dist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by yongtang** [comment]
@zaccharieramzi The tensorflow-io package consists of C++ code that is compiled with Bazel (due to tensorflow's dependency). For that reason  `pip install -e .` needs additional work to make it work (not just python script).

I have changed title to "Support install from source with `pip install -e .`". I will take a look and see if it is possible to make `pip install -e .` with some update.

**Comment by zaccharieramzi** [comment]
Right makes sense, I should have thought about it.

**Comment by yongtang** [comment]
Added PR #959 for the fix. It is now possible to use:
```
TFIO_DATAPATH=<datapath> pip install .
```
for source installation.

It is also possible now to use
```
pip install -e .
```
to install as well. Though after installation with 
```
pip install -e .
```
the `<datapath>` has to be passed through env
```
TFIO_DATAPATH=<datapath> python3 ...
```
during any future python run.

Note install through
```
TFIO_DATAPATH=<datapath> pip install .
```
does not need further passing `TFIO_DATAPATH=<datapath>` after installation.

**Comment by hollowgalaxy** [comment]
What's the recommendation on TFIO_DATAPATH=<datapath>?

**Comment by yongtang** [comment]
@hollowgalaxy you need to build the shared object using bazel first:
```
# Configure the compiler
sudo ./configure.sh

# Build shared libraries
bazel build -s --verbose_failures //tensorflow_io/...
```

After that, you will see a directory `bazel-bin` under your current directory:
```
- io
  - bazel-bin # <= pass to TFIO_DATAPATH=bazel-bin
    - tensorflow_io
      - ... shared library is located
  - tensorflow_io
  - tools
  - third_party
  - setup.py
  ...
```

You will need to pass `TFIO_DATAPATH=bazel-bin` so that shared library `libtensorflow_io.so` could be located by python.
