### ISSUE TITLE
Training local TF model via ArrowStreamDataset raises "ValueError: Cannot take the length of shape with unknown rank."

### ISSUE THREAD

**Issue by JovanVeljanoski** [tensorflow/io#799]
Hello, 

I am trying to use arrow files as data-sources for creating a TF model. I have been following and trying to reproduce  The examples in [this article](https://blog.tensorflow.org/2019/08/tensorflow-with-apache-arrow-datasets.html), however I am running into trouble.

I include the code that I am using at the end of this post, which is the same code as in the article linked above, with the addition of generating a small CSV file as a datasource. 

I am using tensorflow version 2.1.0 and tensorflow_io version 0.11.0.

When I execute the code below, the keras model fitting function raises `ValueError: Cannot take the length of shape with unknown rank.` 

Can you please advise me on this issue? My final goal would be to set up a datasource via the `ArrowStreamDataset` to a tensorflow Estimator.

Here is the code:

```
from functools import partial
import numpy as np
import pandas as pd
import pyarrow.csv
import tensorflow as tf
import tensorflow_io.arrow as arrow_io
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler

# Generate data
X, y = make_classification(n_samples=1_000, n_features=2, n_classes=2, n_redundant=0, n_repeated=0, scale=100)
df = pd.DataFrame(data=X, columns=['x0', 'x1'])
df['label'] = y
df.to_csv(path_or_buf='./testing.csv', index=False)

# Define the model training function
def model_fit(ds):
    """Create and fit a Keras logistic regression model."""
  
    # Build the Keras model
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid'))
    model.compile(optimizer='sgd', loss='mean_squared_error', metrics=['accuracy'])

    # Fit the model on the given dataset
    model.fit(ds, epochs=5, shuffle=False)
    return model

# Function to read a CSV into Arrow data in batches
def read_and_process(filename):
    opts = pyarrow.csv.ReadOptions(block_size=200)
    table = pyarrow.csv.read_csv(filename, read_options=opts)
    
    # Fit the feature transform
    df = table.to_pandas()
    scaler = StandardScaler().fit(df[['x0', 'x1']])
    
    # Iterate over batches in the pyarrow.Table and apply processing
    for batch in table.to_batches():
        df = batch.to_pandas()
        
        # Process the batch and apply feature transforms
        X_scaled = scaler.transform(df[['x0', 'x1']])
        df_scaled = pd.DataFrame({'label': df['label'], 
                                  'x0': X_scaled[:, 0],
                                  'x1': X_scaled[:, 1]})
        
        batch_scaled = pyarrow.RecordBatch.from_pandas(df_scaled, preserve_index=False)
        
        yield batch_scaled

# Build an ArrowStreamDataset to be used with TF
def make_local_dataset(filename):
    # Read the local file and get a record batch iterator
    batch_iter = read_and_process(filename)
    
    # Create the Arrow Dataset as a stream from local iterator of record batches
    ds = arrow_io.ArrowStreamDataset.from_record_batches(batch_iter, 
                                                         output_types=(tf.float64, tf.float64, tf.float64), 
                                                         batch_mode='auto', 
                                                         record_batch_iter_factory=partial(read_and_process, 
                                                                                           filename))
    
    # Map the dataset to combine feature columns to a single tensor
    ds = ds.map(lambda l, x0, x1: (tf.stack([x0, x1], axis=1), l))
    return ds

# Train a model
ds = make_local_dataset(filename='./testing.csv')
model = model_fit(ds)  # <--- The issue is raised here
```

Any help/advice would be highly appreciated

Cheers.

**Comment by BryanCutler** [comment]
Thanks for the report @JovanVeljanoski , I'll take a look

**Comment by BryanCutler** [comment]
@JovanVeljanoski since you are streaming Arrow record batches and don't have the , the output shape is unknown initially. At the time of writing the above example keras could handle that, but since then it seems like something changed and the shape must be specified. If you change the above code to this, it should work (I also needed to change the type of the label column to `tf.int64`):

```python
# Build an ArrowStreamDataset to be used with TF
def make_local_dataset(filename):
    # Read the local file and get a record batch iterator
    batch_iter = read_and_process(filename)
    
    # Create the Arrow Dataset as a stream from local iterator of record batches
    ds = arrow_io.ArrowStreamDataset.from_record_batches(batch_iter, 
                                                         output_types=(tf.int64, tf.float64, tf.float64),
                                                         output_shapes=(tf.TensorShape([]), tf.TensorShape([]), tf.TensorShape([])), 
                                                         batch_mode='auto', 
                                                         record_batch_iter_factory=partial(read_and_process, 
                                                                                           filename))
    
    # Map the dataset to combine feature columns to a single tensor
    ds = ds.map(lambda l, x0, x1: (tf.stack([x0, x1], axis=1), l))
    return ds 
```

If you have the `pyarrow.Schema` initially, there is a helper function to produce the output types and shapes for you:

```python
from tensorflow_io.arrow.python.ops.arrow_dataset_ops import arrow_schema_to_tensor_types
output_types, output_shapes = arrow_schema_to_tensor_types(batch.schema)
```

I'll update the example to reflect this, let me know if this works for you.

**Comment by JovanVeljanoski** [comment]
Hi @BryanCutler 

Thank you for your reply and your help with this. It is much appreciated. 

I tried your fix but I am getting another error. Not sure if this is from the keras side or the arrow/arrowstream side.

This is following the modifications you suggested:
```
model = model_fit(ds)

Epoch 1/5
      1/Unknown - 0s 277ms/step

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/jovan/miniconda3/lib/python3.7/site-packages/tensorflow_io/arrow/python/ops/arrow_dataset_ops.py", line 558, in run_server
    writer.write_batch(batch)
  File "pyarrow/ipc.pxi", line 204, in pyarrow.lib._CRecordBatchWriter.write_batch
  File "/Users/jovan/miniconda3/lib/python3.7/socket.py", line 607, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jovan/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/jovan/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jovan/miniconda3/lib/python3.7/site-packages/tensorflow_io/arrow/python/ops/arrow_dataset_ops.py", line 564, in run_server
    outfile.close()
  File "/Users/jovan/miniconda3/lib/python3.7/socket.py", line 607, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-6-c5315775a9e2> in <module>
----> 1 model = model_fit(ds)

<ipython-input-2-4a2a30efe201> in model_fit(ds)
      8 
      9     # Fit the model on the given dataset
---> 10     model.fit(ds, epochs=5, shuffle=False)
     11     return model

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    340                 mode=ModeKeys.TRAIN,
    341                 training_context=training_context,
--> 342                 total_epochs=epochs)
    343             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    344 

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    630         # Lifting succeeded, so variables are initialized and we can run the
    631         # stateless function.
--> 632         return self._stateless_fn(*args, **kwds)
    633     else:
    634       canon_args, canon_kwds = \

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
   2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 
   2365   @property

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~/miniconda3/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InternalError:  IOError: error reading from socket
	 [[node IteratorGetNext (defined at <ipython-input-2-4a2a30efe201>:10) ]] [Op:__inference_distributed_function_423]

Function call stack:
distributed_function
```

**Comment by BryanCutler** [comment]
Hi @JovanVeljanoski , the model is able to train for me with the above code. Could you post what OS you have and what version of pyarrow is installed?

**Comment by JovanVeljanoski** [comment]
Hi, 

Sure: I am on macOS 10.14.6 (Mojave). The pyarrow version is 0.15.1 (installed from conda-forge). 
tensorflow (v2.1.0, from pip) and tensorflow-io (v.0.11.0 also from pip), all in the same environment of course.

**Comment by maartenbreddels** [comment]
Hi BryanCutler,

thanks for your replies, and nice example @JovanVeljanoski, that made it easy to investigate.

Using the ArrowDataset (without stream), gives a clearer error message:
```
Invalid: Old metadata version not supported
```
Which I traced to https://github.com/apache/arrow/blob/3bc01ec94eb2e310b28402a35196e1e8c5c9aec8/cpp/src/arrow/ipc/message.cc#L54

By downgrading till it works, I found it works with (py)arrow 0.14. What are the plans to go to 0.16 (which should be almost 1.0)? In vaex (https://github.com/vaexio/vaex/) where we plan to use this, we are requiring 0.15, and soon 0.16. Awesome package btw!

Regards,

Maarten

**Comment by yongtang** [comment]
@maartenbreddels the tensorflow-io's master branch has already been upgraded to arrow 0.16.0. We could release another version of tensorflow-io almost any time (with arrow 0.16).

**Comment by maartenbreddels** [comment]
@JovanVeljanoski and I just found out that the nightly pip install seems to work, would be great to see that released!

**Comment by maartenbreddels** [comment]
Thanks for helping out! We have another question, but I'll open a separate issue for that, consider this solved.

**Comment by BryanCutler** [comment]
Thanks @maartenbreddels !  The same issue also came up in #806 and it is caused by a change in the binary IPC protocol with Arrow 0.15.0 (this kind of change will be very rare). I posted some workarounds at https://github.com/tensorflow/io/issues/806#issuecomment-590618541, but in addition to what's already been suggested here, you can set an environment variable as follows, which will allow you to use pyarrow >= 0.15 with tensorflow-io 0.11.0

```
$ export ARROW_PRE_0_15_IPC_FORMAT=1
```

**Comment by maartenbreddels** [comment]
Great, thanks.

Our other issue is solved, it's off topic, but I'll put it here in case someone finds it useful:
The tf LinearRegressor needed a dict of named tensors, but the ArrowDataset could not do this, but using map it was easy to convert to a dictonary of tensors:

We spend a lot of time thinking how to solve this, but it was quite easy in the end, again, your medium article with the .map example gave me the idea:

```python
import numpy as np
import pyarrow as pa
xa = np.arange(10, dtype='f4')
ya = xa**1.2
x = pa.array(xa)
y = pa.array(ya)
batch = pa.RecordBatch.from_arrays([x, y], ['x', 'y'])
schema = batch.schema

import tensorflow as tf
import tensorflow_io.arrow as arrow_io
from tensorflow_io.arrow.python.ops.arrow_dataset_ops import arrow_schema_to_tensor_types

output_types, output_shapes = arrow_schema_to_tensor_types(schema)
 
def input_fn():
    ds = arrow_io.ArrowDataset.from_record_batches([batch], 
                                                     output_types=output_types,
                                                     output_shapes=output_shapes,
                                                     batch_mode='auto', )
    # This will make it work with the Regressor, since it wants a dict
    ds = ds.map(lambda x, y: ({'x': x}, y))
    return ds

feature_columns = [tf.feature_column.numeric_column(key='x', shape=(1,), dtype=tf.float32)]
model = tf.estimator.LinearRegressor(feature_columns=feature_columns)
model.train(input_fn, max_steps=10)
```

**Comment by yongtang** [comment]
On a side note, it might be possible to generate the `map` automatically from implementation point of view: tensorflow has a `tf.nest.flatten` and `tf.nest.pack_sequence_as` which could convert an arbitrary structure into a flat tuple and back. So in theory, if the expected map is known in advance, then it could be converted to a tuple in a definitely way with `tf.nest.flatten` . Then this tuple could be passed to C++ op to get the value back in the sample way (as a tuple), and apply `tf.nest.pack_sequence_as` will get back the original structure.

SqlIODataset is a recent example of `tf.nest.flatten`/`tf.nest.pack_sequence_as`  in a similar way. @BryanCutler maybe this could be something we consider for potential enhancement?

**Comment by BryanCutler** [comment]
Thanks for the tip @maartenbreddels , that is very helpful to know!

>SqlIODataset is a recent example of tf.nest.flatten/tf.nest.pack_sequence_as in a similar way. @BryanCutler maybe this could be something we consider for potential enhancement?
@yongtang yeah this sound like a great idea for an enhancement!

**Comment by yongtang** [comment]
Added #813 to capture the tensorflow-io 0.12.0 release (which consists of arrow 0.16.0) tracking.

**Comment by BryanCutler** [comment]
Now that tensorflow-io 0.12.0 has been released, I'll go ahead and close this.

**Comment by maartenbreddels** [comment]
Thanks!

(from mobile phone)
