### ISSUE TITLE
[tensorflow_io.oss] Fail to use tf.gfile.Rename to rename oss directory

### ISSUE THREAD

**Issue by zouxu09** [tensorflow/io#834]
Code to reproduce:
```python
import tensorflow as tf
import tensorflow_io.oss

# fill with your configs
endpoint = ''
bucket = ''
access_id = ''
access_key = ''

baseOssPath = "oss://%s\x01id=%s\x02key=%s\x02host=%s/" % (
    bucket, access_id, access_key, endpoint)

tf.gfile.Rename(baseOssPath + "dir/", baseOssPath + "dir_copy/")
``` 

Error message:
```bash
Traceback (most recent call last):
  File "/tmp/t.py", line 30, in <module>
    tf.gfile.Rename(baseOssPath + "dir/", baseOssPath + "dir_copy/")
  File "/home/admin/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 445, in rename
    compat.as_bytes(oldname), compat.as_bytes(newname), overwrite, status)
  File "/home/admin/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: <****> errMsg: object not exists!
```

**Comment by zouxu09** [comment]
@yongtang Could you please assign this issue to me? I'd like to fix this

**Comment by terrytangyuan** [comment]
Could you try assigning yourself? GitHub doesn’t allow us to assign this to you since you are not a member of TensorFlow GitHub org.

**Comment by yongtang** [comment]
I think it is possible to assign as long as you are the issue author.
