### ISSUE TITLE
from_hdf5 fails with cryptic error messages

### ISSUE THREAD

**Issue by nalyat** [tensorflow/io#841]
in version 0.12.0, installed from pip, I'm trying to use from_hdf function to create datasets, sample code is as follows:
```
import glob

import h5py
import os
import tensorflow_io as tfio
import tensorflow as tf
import numpy as np


def create_datasets(runpath, fileCnt=10):
    os.makedirs(runpath, exist_ok=True)
    for i in range(fileCnt):
        f = h5py.File(f'{runpath}/file_{i}.h5', 'w')
        totalSamples = np.random.randint(50000, 100000)
        f.create_dataset('features', data=np.random.random((totalSamples, 60)))
        f.create_dataset('targets', data=np.random.random((totalSamples, 3)))
        f.close()


def get_paths(runpath):
    return glob.glob(f'{runpath}/*.h5')


if __name__ == '__main__':
    runpath = '/tmp/data'
    if not os.path.exists(runpath):
        create_datasets(runpath)

    cnt = 0
    for p in get_paths(runpath):
        try:
            features = tfio.IODataset.from_hdf5(p, '/features')
            targets = tfio.IODataset.from_hdf5(p, '/targets')
            dataset = tf.data.Dataset.zip((features, targets))

            for t in dataset:
                cnt += t[0].shape[0]
                
        except Exception as e:
            print(f"Failed going through {p}")
            raise e
        print(f"Success going through {p}")


    print(f"Iterated {cnt} items")
```

Although the first file always succeeds, consecutive files (may) fail, where I get an error like:

```
Success going through /tmp/data/file_0.h5
2020-03-06 14:54:30.187273: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at hdf5_kernels.cc:612 : Invalid argument: dimension [0] out of boundary: start=64512, slice=1024, boundary=65153
2020-03-06 14:54:30.187548: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at hdf5_kernels.cc:612 : Invalid argument: dimension [0] out of boundary: start=64512, slice=1024, boundary=65153
2020-03-06 14:54:30.187601: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at iterator_ops.cc:941 : Invalid argument: dimension [0] out of boundary: start=64512, slice=1024, boundary=65153
         [[{{node IO>HDF5ReadableRead}}]]
Failed going through /tmp/data/file_1.h5
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 1897, in execution_mode
    yield
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 659, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2479, in iterator_get_next_sync
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: dimension [0] out of boundary: start=64512, slice=1024, boundary=65153
         [[{{node IO>HDF5ReadableRead}}]] [Op:IteratorGetNextSync]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/test.py", line 40, in <module>
    raise e
  File "/tmp/test.py", line 35, in <module>
    for t in dataset:
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/opt/anaconda/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 1900, in execution_mode
    executor_new.wait()
  File "/opt/anaconda/lib/python3.7/site-packages/tensorflow_core/python/eager/executor.py", line 67, in wait
    pywrap_tensorflow.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: dimension [0] out of boundary: start=64512, slice=1024, boundary=65153
         [[{{node IO>HDF5ReadableRead}}]]

```

Is this an expected error? If so, is it possible to make the error reason more apparent?

**Comment by yongtang** [comment]
@nalyat  @zaccharieramzi  Created PR #899 for the fix.

**Comment by zaccharieramzi** [comment]
@yongtang Thanks so much! Could you explain what you mean by "reused in graph incrorrectly"?

**Comment by yongtang** [comment]
The hdf5 kernel ops will create a resource type in the tf graph, and a subsequent read op with resource passed as the reference. For some reason the resource lookup in tf graph always find the previous resource (the first hdf5) which should not happen. That was not the case in last version of the TF (2.1 or earlier). Not sure exactly what changed in behavior in TF, but I have created a uuid generated name as the reference for resource. That looks like solves the issue at least for hdf5.
