### ISSUE TITLE
avro type unssupported error

### ISSUE THREAD

**Issue by dav009** [tensorflow/io#986]
👋   I am trying to load an avro file as a ds, but I am getting the error below:

```
>> During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_io/core/python/ops/io_dataset.py", line 220, in from_avro
    filename, schema, columns=columns, internal=True
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_io/core/python/ops/avro_dataset_ops.py", line 62, in __init__
    shared_name="{}/{}".format(filename, uuid.uuid4().hex),
  File "<string>", line 2536, in io_avro_readable_init
  File "<string>", line 2594, in io_avro_readable_init_eager_fallback
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Avro type unsupported: 10 [Op:IO>AvroReadableInit]
```

this is the code snippet with the avro schema:

```python
import tensorflow_io as tfio
schema = """{
  "type" : "record",
  "name" : "topLevelRecord",
  "fields" : [ {
    "name" : "number_of_mentions",
    "type" : [ "long", "null" ]
  }, {
    "name" : "tweet_id",
    "type" : [ "long", "null" ]
  }, {
    "name" : "tweet_type",
    "type" : [ "long", "null" ]
  }, {
    "name" : "language",
    "type" : [ "long", "null" ]
  }, {
    "name" : "tweet_timestamp",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaged_with_user_id",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaged_with_user_follower_count",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaged_with_user_following_count",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaged_with_user_account_creation",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaging_user_id",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaging_user_follower_count",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaging_user_following_count",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engaging_user_account_creation",
    "type" : [ "long", "null" ]
  }, {
    "name" : "reply_timestamp",
    "type" : [ "long", "null" ]
  }, {
    "name" : "retweet_timestamp",
    "type" : [ "long", "null" ]
  }, {
    "name" : "retweet_with_comment_timestamp",
    "type" : [ "long", "null" ]
  }, {
    "name" : "like_timestamp",
    "type" : [ "long", "null" ]
  }, {
    "name" : "engagee_follows_engager_int",
    "type" : [ "int", "null" ]
  }, {
    "name" : "engaging_user_is_verified_int",
    "type" : [ "int", "null" ]
  }, {
    "name" : "engaged_with_user_is_verified_int",
    "type" : [ "int", "null" ]
  }, {
    "name" : "starts_with_mention_int",
    "type" : [ "int", "null" ]
  }, {
    "name" : "text_embedding",
    "type" : [ {
      "type" : "array",
      "items" : [ "double", "null" ]
    }, "null" ]
  }, {
    "name" : "sentence_embedding",
    "type" : [ {
      "type" : "array",
      "items" : [ "double", "null" ]
    }, "null" ]
  }, {
    "name" : "hashtags",
    "type" : [ {
      "type" : "array",
      "items" : [ "long", "null" ]
    }, "null" ]
  }, {
    "name" : "present_media",
    "type" : [ {
      "type" : "array",
      "items" : [ "long", "null" ]
    }, "null" ]
  }, {
    "name" : "present_links",
    "type" : [ {
      "type" : "array",
      "items" : [ "long", "null" ]
    }, "null" ]
  }, {
    "name" : "present_domains",
    "type" : [ {
      "type" : "array",
      "items" : [ "long", "null" ]
    }, "null" ]
  } ]
}"""
ds  = tfio.IODataset.from_avro("avro_file", schema)

```

I guess this error is coming from here https://github.com/tensorflow/io/blob/master/tensorflow_io/core/kernels/avro_kernels.cc#L360 but I cant find what `10` corresponds in `avro::`'s type enum. 

I wonder if the error is due to arrays. 

Please note that I got the schema of the avro file by using:
`java -jar avro-tools-1.9.2.jar  getschema avro_file`

---

generated a dummy avro file with and without an array, the one with an array threw the error mentioned above.

```
schema = """
{
  "type" : "record",
  "name" : "topLevelRecord",
  "fields" : [ {
    "name" : "_1",
    "type" : [ {
      "type" : "array",
      "items" : "double"
    }, "null" ]
  }, {
    "name" : "_2",
    "type" : [ "string", "null" ]
  }, {
    "name" : "_3",
    "type" : [ "string", "null" ]
  }, {
    "name" : "_4",
    "type" : [ "string", "null" ]
  } ]
}
"""
avro = tfio.IODataset.from_avro(avro_file_path,schema)
```

**Comment by yongtang** [comment]
@dav009 `10` is mapped to `AVRO_ARRAY` which was not supported. Though the recent experimental implementation of `tfio.experimental.columnar.AvroRecordDataset` might have `AVRO_ARRAY` support. I will take a look.

**Comment by dav009** [comment]
@yongtang `tfio.experimental.columnar.AvroRecordDataset` worked 👍  thank you!
