### ISSUE TITLE
Avro files with array field: "Expected type 'int' but got type 'array'."

### ISSUE THREAD

**Issue by dav009** [tensorflow/io#990]
👋 

I am trying to generate a dataset out of avro files containing a int array field.
I am using the code snippet below which is similar to that of a unit test [here](https://github.com/tensorflow/io/blob/master/tests/test_parse_avro_eager.py#L545)

I can provide the avro files if needed, but it is just a dummy sample dataset exported from spark.

```python
import tensorflow_io as tfio
import tensorflow as tf
schema = """
{
  "type" : "record",
  "name" : "topLevelRecord",
  "fields" : [ {
    "name" : "a",
    "type" : [ {
      "type" : "array",
      "items" : "int"
    }, "null" ]
  }, {
    "name" : "b",
    "type" : [ "string", "null" ]
  }, {
    "name" : "c",
    "type" : [ "string", "null" ]
  }, {
    "name" : "d",
    "type" : [ "string", "null" ]
  } ]
}
"""




features = {"a": tf.io.FixedLenFeature([], tf.dtypes.int32),
            "b":  tf.io.FixedLenFeature([], tf.dtypes.string),
            "c":  tf.io.FixedLenFeature([], tf.dtypes.string),
            "d":  tf.io.FixedLenFeature([], tf.dtypes.string),
}

ds = tfio.experimental.columnar.make_avro_record_dataset(file_pattern=["/folder/avro_sample/*.avro"], features=features, batch_size=1, reader_schema=schema)

for i in iter(ds):
    print(i)

```

I get the following error: 
```
Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.
2020-06-04 13:18:28.900511: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
Traceback (most recent call last):
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
2020-06-04 13:18:28.900932: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
2020-06-04 13:18:28.901230: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
    yield
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
2020-06-04 13:18:28.901547: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
    output_shapes=self._flat_output_shapes)
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
2020-06-04 13:18:28.901894: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
2020-06-04 13:18:28.902239: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
    _ops.raise_from_not_ok_status(e, name)
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
2020-06-04 13:18:28.902553: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
2020-06-04 13:18:28.902894: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
2020-06-04 13:18:28.903191: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
2020-06-04 13:18:28.903472: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at parse_avro_kernels.cc:463 : Invalid argument: Expected type 'int' but got type 'array'.
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected type 'int' but got type 'array'.
	 [[{{node ParseAvro/IO>ParseAvro}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 62, in <module>
    for i in iter(ds):
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/miniconda/envs/tfio-dev/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/miniconda/envs/tfio-dev/lib/python3.6/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected type 'int' but got type 'array'.
	 [[{{node ParseAvro/IO>ParseAvro}}]]
```

**Comment by burgerkingeater** [comment]
@dav009  can you try `a[*]` instead of `a` in features? [RFC](https://github.com/tensorflow/io/blob/98f52b669496602757ee801afa6b91fab041482b/tensorflow_io/core/kernels/20190307-avro-dataset.md) has more detailed regarding avro reader, please let us know if you have further question.

**Comment by kvignesh1420** [comment]
@dav009 any updates on this?

**Comment by kvignesh1420** [comment]
Closing due to inactivity. Please reopen if required.
